// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComponentsAsyncDataComponent: typeof import('./src/components/AsyncDataComponent.vue')['default']
    ComponentsSocialWallSocialWall: typeof import('./src/components/social-wall/SocialWall.vue')['default']
    ComponentsSocialWallSocialWallSearch: typeof import('./src/components/social-wall/SocialWallSearch.vue')['default']
    ComponentsSocialWallSocialWallTags: typeof import('./src/components/social-wall/SocialWallTags.vue')['default']
    ComponentsSocialWallSocialWallVideoPlayer: typeof import('./src/components/social-wall/SocialWallVideoPlayer.vue')['default']
    ComponentsSocialWallSocialWallVideos: typeof import('./src/components/social-wall/SocialWallVideos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
